# Generated by Django 4.0.8 on 2026-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='honorific',
            field=models.CharField(blank=True, help_text='e.g. Dr., Prof., Mr., Mrs.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='Student matric number', max_length=30, null=True),
        ),
    ]
